
services:
  mongodb:
    # MongoDB'nin en güncel resmi imajı internetten çekilir.
    image: mongo:latest
    
    # Konteynerin adı belirlenir.
    container_name: kahoot_mongo_db
    
    # Bilgisayarının 27017 portu, konteynerin 27017 portuyla eşleştirilir.
    ports:
      - "27017:27017"
      
    # Konteyner kapansa bile verilerin silinmemesi için kalıcı bir hafıza (volume) oluşturulur.
    volumes:
      - mongo_data:/data/db

  redis:
    # Redis'in hafif ve hızlı olan alpine sürümü çekilir.
    image: redis:alpine
    container_name: kahoot_redis
    # Uygulamanın Redis'e bağlanabilmesi için varsayılan port dışarı açılır.
    ports:
      - "6379:6379"

  api:
    # API'mizi az önce yazdığımız Dockerfile üzerinden derlemesini söylüyoruz.
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - Redis__ConnectionString=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    # API'nin çalışması için önce DB ve Redis'in hazır olmasını bekliyoruz.
    depends_on:
      - mongodb
      - redis

  # Yük Dengeleyici (Load Balancer) - Tüm dış trafiği bu servis karşılar
  nginx:
    image: nginx:alpine
    container_name: kahoot_nginx
    ports:
      - "5252:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  # Veritabanı dosyalarının fiziksel olarak tutulacağı alan tanımlanır.
  mongo_data: